User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
> python3.7 ~/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda --version
> pyenv root
> conda info --json
> pyenv root
Python interpreter path: /usr/bin/python3
Starting Pylance language server.
Error 2021-06-16 14:00:33: Failed to start language server, Class name = r, completed in 0ms, has a falsy return value, Arg 1: <Uri:/home/user/gittest/https-gitlab.scriptbees.com-pharmacovigilance-casemanagementsystem-cm-crawl>, Arg 2: {"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.6.9","major":3,"minor":6,"patch":9,"prerelease":[],"build":[],"version":"3.6.9"},"sysVersion":"3.6.9 (default, Jul 17 2020, 12:50:27) \n[GCC 8.4.0]","sysPrefix":"/usr","fileHash":"e6653bbfee1ccccf516f5b7b6a16ad603a629e40d0af8c24eb6e0aba3befea72e976e937075949998a05186032e882f7169465e05e09cfaad72159b287511fa6","envType":"Unknown","displayName":"Python 3.6.9 64-bit","store":true}, Return Value: undefined [Error: ms-python.vscode-pylance not installed
	at d.getCurrentLanguageServerDirectory (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:233011)
	at async r.start (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:239427)]
Error 2021-06-16 14:00:33: [Error: ms-python.vscode-pylance not installed
	at d.getCurrentLanguageServerDirectory (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:233011)
	at async r.start (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:239427)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-16 14:00:33: Failed to activate language server, Class name = a, completed in 5ms, has a falsy return value, Arg 1: <Uri:/home/user/gittest/https-gitlab.scriptbees.com-pharmacovigilance-casemanagementsystem-cm-crawl>, Arg 2: {"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.6.9","major":3,"minor":6,"patch":9,"prerelease":[],"build":[],"version":"3.6.9"},"sysVersion":"3.6.9 (default, Jul 17 2020, 12:50:27) \n[GCC 8.4.0]","sysPrefix":"/usr","fileHash":"e6653bbfee1ccccf516f5b7b6a16ad603a629e40d0af8c24eb6e0aba3befea72e976e937075949998a05186032e882f7169465e05e09cfaad72159b287511fa6","envType":"Unknown","displayName":"Python 3.6.9 64-bit","store":true}, Return Value: undefined [Error: ms-python.vscode-pylance not installed
	at d.getCurrentLanguageServerDirectory (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:233011)
	at async r.start (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:239427)]
Error 2021-06-16 14:00:33: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/user/gittest/https-gitlab.scriptbees.com-pharmacovigilance-casemanagementsystem-cm-crawl/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/user/gittest/https-gitlab.scriptbees.com-pharmacovigilance-casemanagementsystem-cm-crawl/.vscode/settings.json')
	at _handleError (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:156273)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:581560)
	at async /home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/home/user/.vscode-insiders/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
Error 2021-06-16 14:00:53: Error in prompting to install insiders, Class name = f, completed in 20121ms, has a falsy return value, , Return Value: undefined [Canceled: Canceled
	at Object.r [as canceled] (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8267
	at Array.forEach (<anonymous>)
	at dispose (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8215)
	at w.terminate (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:684)
	at u (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:31806)
	at Socket.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29568)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)]
Error 2021-06-16 14:00:53: Failure during activation. [Canceled: Canceled
	at Object.r [as canceled] (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8267
	at Array.forEach (<anonymous>)
	at dispose (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8215)
	at w.terminate (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:684)
	at u (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:31806)
	at Socket.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29568)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)]
Error 2021-06-16 14:00:53: sendStartupTelemetry() failed. [Canceled: Canceled
	at Object.r [as canceled] (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8267
	at Array.forEach (<anonymous>)
	at dispose (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8215)
	at w.terminate (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:684)
	at u (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:31806)
	at Socket.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29568)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)]
